version: '3'
services:
  spring_app:
    image: seongbin9786/classvar_backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE} # 지금은 prod 세팅이 없음
      - SSL_PKCS12_PASSWORD=${SSL_PKCS12_PASSWORD}
      - JAVA_OPTS="-XX:ReservedCodeCacheSize=100M" # 1GB limit인 EC2에서 실행이 안 돼서 추가함
      # 최초 로딩 종료 시 440MB, 기본 Ubuntu 사용량 220MB, 실제 사용 시 어떻게 될진 모르겠음. 모니터링 필요음
    mem_limit: 800m # 컨테이너의 메모리 제한을 제공 (Buildpack 관련 설정 방법을 찾지 못해서 컨테이너 메모리 설정으로 우회함)
    # 참고: https://baeji77.github.io/spring/dev/Spring-boot-gradle-build/
    ports:
      # Spring App에선 8080 포트로 열려있기 때문에.
      - 80:8080
      - 443:8443 # Support HTTPS