# Support HTTPS
server:
  address: api.classvar.com
  port: 443
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: classpath:SSL_CERTIFICATE.p12 # /를 앞에 포함하면 안 되는데 이유는 모르겠다.
    key-store-type: PKCS12
    key-store-password: ${SSL_PKCS12_PASSWORD}
