# Support HTTPS
server:
  address: localhost
  port: 443
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: classpath:SSL_CERTIFICATE_local.p12 # test
    key-store-type: PKCS12
    key-store-password: ${SSL_PKCS12_PASSWORD}
